export const CASES_SUMMARY = {
  CONFIRMED: "Confirmed",
  RECOVERED: "Recovered",
  ACTIVE: "Active",
  DEATHS: "Deaths",
};

export const LOCATION_META = {
  WORLD: "WORLD",
  INDIA: "INDIA",
  INDIA_STATE: "INDIA_STATE",
};

export const COMPARE_COLORS = [
  "#4285F4",
  "#DB4437",
  "#FFCA28",
  "#43A047",
  "#9C27B0",
];

export const countries = [
  "USA",
  "Spain",
  "Italy",
  "France",
  "Germany",
  "UK",
  "Iran",
  "Turkey",
  "Belgium",
  "Netherlands",
  "Switzerland",
  "Canada",
  "Brazil",
  "Portugal",
  "Russia",
  "Austria",
  "Israel",
  "S. Korea",
  "Sweden",
  "India",
  "Ireland",
  "Ecuador",
  "Chile",
  "Peru",
  "Japan",
  "Poland",
  "Norway",
  "Australia",
  "Romania",
  "Denmark",
  "Czechia",
  "Pakistan",
  "Malaysia",
  "Philippines",
  "Saudi Arabia",
  "Indonesia",
  "Mexico",
  "UAE",
  "Serbia",
  "Luxembourg",
  "Panama",
  "Qatar",
  "Finland",
  "Dominican Republic",
  "Ukraine",
  "Colombia",
  "Belarus",
  "Thailand",
  "Singapore",
  "Argentina",
  "Greece",
  "South Africa",
  "Egypt",
  "Algeria",
  "Iceland",
  "Moldova",
  "Morocco",
  "Croatia",
  "Hungary",
  "Iraq",
  "New Zealand",
  "Estonia",
  "Kuwait",
  "Slovenia",
  "Azerbaijan",
  "Bahrain",
  "Lithuania",
  "Armenia",
  "Hong Kong",
  "Bosnia and Herzegovina",
  "Kazakhstan",
  "Uzbekistan",
  "North Macedonia",
  "Cameroon",
  "Slovakia",
  "Diamond Princess",
  "Tunisia",
  "Bulgaria",
  "Cuba",
  "Latvia",
  "Andorra",
  "Cyprus",
  "Lebanon",
  "Bangladesh",
  "Afghanistan",
  "Oman",
  "Costa Rica",
  "Ivory Coast",
  "Uruguay",
  "Niger",
  "Burkina Faso",
  "Albania",
  "Ghana",
  "Channel Islands",
  "Honduras",
  "Taiwan",
  "Réunion",
  "Jordan",
  "Malta",
  "Kyrgyzstan",
  "San Marino",
  "Mauritius",
  "Nigeria",
  "Bolivia",
  "Palestine",
  "Senegal",
  "Montenegro",
  "Vietnam",
  "Georgia",
  "Guinea",
  "DRC",
  "Isle of Man",
  "Djibouti",
  "Sri Lanka",
  "Kenya",
  "Mayotte",
  "Faeroe Islands",
  "Venezuela",
  "Martinique",
  "Guatemala",
  "Guadeloupe",
  "Brunei",
  "Paraguay",
  "Gibraltar",
  "El Salvador",
  "Cambodia",
  "Rwanda",
  "Trinidad and Tobago",
  "Madagascar",
  "Mali",
  "Monaco",
  "Aruba",
  "French Guiana",
  "Liechtenstein",
  "Togo",
  "Ethiopia",
  "Jamaica",
  "Barbados",
  "Congo",
  "Cayman Islands",
  "Uganda",
  "French Polynesia",
  "Sint Maarten",
  "Liberia",
  "Bermuda",
  "Gabon",
  "Bahamas",
  "Guyana",
  "Macao",
  "Zambia",
  "Myanmar",
  "Guinea-Bissau",
  "Benin",
  "Eritrea",
  "Haiti",
  "Tanzania",
  "Saint Martin",
  "Syria",
  "Libya",
  "Antigua and Barbuda",
  "Somalia",
  "Equatorial Guinea",
  "Mozambique",
  "Maldives",
  "Angola",
  "Sudan",
  "Laos",
  "Chad",
  "New Caledonia",
  "Dominica",
  "Fiji",
  "Mongolia",
  "Namibia",
  "Saint Lucia",
  "Zimbabwe",
  "Curaçao",
  "Grenada",
  "Eswatini",
  "Belize",
  "Malawi",
  "Botswana",
  "Nepal",
  "Saint Kitts and Nevis",
  "St. Vincent Grenadines",
  "Greenland",
  "Seychelles",
  "Suriname",
  "Sierra Leone",
  "MS Zaandam",
  "Gambia",
  "Nicaragua",
  "Turks and Caicos",
  "Montserrat",
  "Cabo Verde",
  "CAR",
  "Vatican City",
  "Mauritania",
  "St. Barth",
  "Western Sahara",
  "Bhutan",
  "Burundi",
  "Falkland Islands",
  "Sao Tome and Principe",
  "South Sudan",
  "Anguilla",
  "British Virgin Islands",
  "Caribbean Netherlands",
  "Papua New Guinea",
  "Timor-Leste",
  "Saint Pierre Miquelon",
  "Yemen",
  "China",
];

export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const COMPARE_LOCATIONS = [...countries, ...indianStates];

export const indiaStateCodes = {
  AP: "Andhra Pradesh",
  AR: "Arunachal Pradesh",
  AS: "Assam",
  BR: "Bihar",
  CT: "Chhattisgarh",
  GA: "Goa",
  GJ: "Gujarat",
  HR: "Haryana",
  HP: "Himachal Pradesh",
  JH: "Jharkhand",
  KA: "Karnataka",
  KL: "Kerala",
  MP: "Madhya Pradesh",
  MH: "Maharashtra",
  MN: "Manipur",
  ML: "Meghalaya",
  MZ: "Mizoram",
  NL: "Nagaland",
  OR: "Odisha",
  PB: "Punjab",
  RJ: "Rajasthan",
  SK: "Sikkim",
  TN: "Tamil Nadu",
  TG: "Telangana",
  TR: "Tripura",
  UT: "Uttarakhand",
  UP: "Uttar Pradesh",
  WB: "West Bengal",
  AN: "Andaman and Nicobar Islands",
  CH: "Chandigarh",
  DB: "Dadra and Nagar Haveli",
  DD: "Daman and Diu",
  DL: "Delhi",
  JK: "Jammu and Kashmir",
  LA: "Ladakh",
  LD: "Lakshadweep",
  PY: "Puducherry",
  TT: "INDIA",
};

export const indiaColInfo = [
  {
    label: "State",
    id: "state",
    mLabel: "",
    sLabel: "",
    subTextKey: "testedData",
    leftAlign: true,
  },
  {
    label: "Confirmed",
    mLabel: "Confmd",
    sLabel: "C",
    id: "confirmed",
    newId: "deltaconfirmed",
    newLabel: "new",
    newClassName: "new-cases",
    sortable: true,
  },
  {
    label: "Active",
    mLabel: "Actv",
    sLabel: "A",
    id: "active",
    sortable: true,
  },
  {
    label: "Recovered",
    mLabel: "Rcrvd",
    sLabel: "R",
    id: "recovered",
    newId: "deltarecovered",
    newLabel: "new",
    newClassName: "new-recovered",
    sortable: true,
  },
  {
    label: "Deaths",
    mLabel: "Dths",
    sLabel: "D",
    id: "deaths",
    newId: "deltadeaths",
    newLabel: "new",
    newClassName: "new-deaths",
    sortable: true,
  },
];

export const districtColInfo = [
  {
    label: "District",
    mLabel: "District",
    sLabel: "Dstrt",
    leftAlign: true,
    id: "name",
  },
  {
    label: "Confirmed",
    mLabel: "Confmd",
    sLabel: "C",
    id: "confirmed",
    newId: "new_confirmed",
    newLabel: "new",
    newClassName: "new-cases",
    sortable: true,
  },
];

export const worldColInfo = [
  {
    label: "Country",
    mLabel: "",
    sLabel: "",
    id: "country",
    leftAlign: true,
  },
  {
    label: "Confirmed",
    mLabel: "Confmd",
    sLabel: "C",
    id: "cases",
    newId: "new_cases",
    newLabel: "new",
    newClassName: "new-cases",
    sortable: true,
  },
  {
    label: "Active",
    mLabel: "Actv",
    sLabel: "A",
    id: "active_cases",
    sortable: true,
  },

  {
    label: "Recovered",
    mLabel: "Rcrvd",
    sLabel: "R",
    id: "total_recovered",
    sortable: true,
  },
  {
    label: "Deaths",
    mLabel: "Dths",
    sLabel: "D",
    id: "deaths",
    newId: "new_deaths",
    newLabel: "new",
    newClassName: "new-deaths",
    sortable: true,
  },
];
